#include "src/game/envfx_snow.h"

const GeoLayout car_Armature_002[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 152, 84, -57, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 133, 0, car_Mario_002_Mario_001_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout car_Armature_001[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 67, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 33, 0, car_Top_002_Top_001_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, car_Top_002_Top_001_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout car_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, -90, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 36, 0, car_Base_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_ALPHA, car_Base_mesh_layer_4),
					GEO_SWITCH_CASE(0, geo_switch_mario_in_car),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 152, 129, -57, car_Mario_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_BRANCH(1, car_Armature_002),
					GEO_CLOSE_NODE(),
					GEO_SWITCH_CASE(0, geo_switch_car_top),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 99, 0, NULL),
						GEO_CLOSE_NODE(),
						GEO_BRANCH(1, car_Armature_001),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -147, 19, -136, -90, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, car_WheelBL_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -147, 19, 141, 0, 90, 90),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, car_WheelBR_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 155, 19, -136, -90, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, car_WheelFL_mesh_layer_1),
					GEO_CLOSE_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 155, 19, 141, 0, 90, 90),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, car_WheelFR_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, car_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, car_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, car_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
