extern const GeoLayout bowser_1_area_1_geo[];
extern const GeoLayout bowser_1_area_1[];
extern const Collision bowser_1_area_1_collision[];
extern const MacroObject bowser_1_area_1_macro_objs[];
extern Lights1 bowser_1_dl_f3d_material_001_lights;
extern Lights1 bowser_1_dl_f3d_material_lights;
extern Lights1 bowser_1_dl_f3d_material_002_lights;
extern u8 bowser_1_dl_DA_0x2CA0_32x32_RGBA16_ci8[];
extern u8 bowser_1_dl_DA_0x2CA0_32x32_RGBA16_ci8_pal_rgba16[];
extern u8 bowser_1_dl_hotrod_ci8[];
extern u8 bowser_1_dl_hotrod_ci8_pal_rgba16[];
extern u8 bowser_1_dl_Tile0134_RGB_ci8[];
extern u8 bowser_1_dl_Tile0134_RGB_ci8_pal_rgba16[];
extern Vtx bowser_1_dl_Circle_mesh_layer_1_vtx_0[40];
extern Gfx bowser_1_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx bowser_1_dl_Circle_mesh_layer_1_vtx_1[128];
extern Gfx bowser_1_dl_Circle_mesh_layer_1_tri_1[];
extern Vtx bowser_1_dl_Circle_mesh_layer_1_vtx_2[8];
extern Gfx bowser_1_dl_Circle_mesh_layer_1_tri_2[];
extern Gfx mat_bowser_1_dl_f3d_material_001[];
extern Gfx mat_revert_bowser_1_dl_f3d_material_001[];
extern Gfx mat_bowser_1_dl_f3d_material[];
extern Gfx mat_revert_bowser_1_dl_f3d_material[];
extern Gfx mat_bowser_1_dl_f3d_material_002[];
extern Gfx mat_revert_bowser_1_dl_f3d_material_002[];
extern Gfx bowser_1_dl_Circle_mesh_layer_1[];
extern Gfx bowser_1_dl_material_revert_render_settings[];
