extern Lights1 freddydl_f3d_material_lights;
extern u8 freddydl_AAAHHH_ci8[];
extern u8 freddydl_AAAHHH_ci8_pal_rgba16[];
extern Vtx freddydl_freddy_mesh_vtx_cull[8];
extern Vtx freddydl_freddy_mesh_vtx_0[4];
extern Gfx freddydl_freddy_mesh_tri_0[];
extern Gfx mat_freddydl_f3d_material[];
extern Gfx mat_revert_freddydl_f3d_material[];
extern Gfx freddydl_freddy_mesh[];
