extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_f3d_material_002_lights;
extern Lights1 ccm_dl_f3d_material_lights;
extern u8 ccm_dl_Tile0843_RGB_ci8[];
extern u8 ccm_dl_Tile0843_RGB_ci8_pal_rgba16[];
extern u8 ccm_dl_demonn_i8[];
extern u8 ccm_dl_core_i8[];
extern u8 ccm_dl_Tile0347_RGB_ci8[];
extern u8 ccm_dl_Tile0347_RGB_ci8_pal_rgba16[];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_0[108];
extern Gfx ccm_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_1[395];
extern Gfx ccm_dl_Circle_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Circle_mesh_layer_1_vtx_2[356];
extern Gfx ccm_dl_Circle_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_ccm_dl_f3d_material_002[];
extern Gfx mat_revert_ccm_dl_f3d_material_002[];
extern Gfx mat_ccm_dl_f3d_material_001[];
extern Gfx mat_revert_ccm_dl_f3d_material_001[];
extern Gfx mat_ccm_dl_f3d_material_003[];
extern Gfx mat_revert_ccm_dl_f3d_material_003[];
extern Gfx mat_ccm_dl_f3d_material[];
extern Gfx mat_revert_ccm_dl_f3d_material[];
extern Gfx ccm_dl_Circle_mesh_layer_1[];
extern Gfx ccm_dl_Plane_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
