extern const GeoLayout thi_area_1_geo[];
extern const GeoLayout thi_area_1[];
extern const Collision thi_area_1_collision[];
extern const MacroObject thi_area_1_macro_objs[];
extern Lights1 thi_dl_f3d_material_lights;
extern Vtx thi_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx thi_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx thi_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Cube_002_mesh_layer_1_vtx_0[24];
extern Gfx thi_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Cube_003_mesh_layer_1_vtx_0[24];
extern Gfx thi_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Cube_004_mesh_layer_1_vtx_0[24];
extern Gfx thi_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Cube_005_mesh_layer_1_vtx_0[24];
extern Gfx thi_dl_Cube_005_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Cube_006_mesh_layer_1_vtx_0[24];
extern Gfx thi_dl_Cube_006_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Cube_007_mesh_layer_1_vtx_0[24];
extern Gfx thi_dl_Cube_007_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Cube_008_mesh_layer_1_vtx_0[24];
extern Gfx thi_dl_Cube_008_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Cube_009_mesh_layer_1_vtx_0[24];
extern Gfx thi_dl_Cube_009_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Cube_010_mesh_layer_1_vtx_0[24];
extern Gfx thi_dl_Cube_010_mesh_layer_1_tri_0[];
extern Gfx mat_thi_dl_f3d_material[];
extern Gfx thi_dl_Cube_mesh_layer_1[];
extern Gfx thi_dl_Cube_001_mesh_layer_1[];
extern Gfx thi_dl_Cube_002_mesh_layer_1[];
extern Gfx thi_dl_Cube_003_mesh_layer_1[];
extern Gfx thi_dl_Cube_004_mesh_layer_1[];
extern Gfx thi_dl_Cube_005_mesh_layer_1[];
extern Gfx thi_dl_Cube_006_mesh_layer_1[];
extern Gfx thi_dl_Cube_007_mesh_layer_1[];
extern Gfx thi_dl_Cube_008_mesh_layer_1[];
extern Gfx thi_dl_Cube_009_mesh_layer_1[];
extern Gfx thi_dl_Cube_010_mesh_layer_1[];
extern Gfx thi_dl_material_revert_render_settings[];
